package edu.hm.cs.fs.common.constant;

/**
 * Created by Fabio on 26.03.2015.
 * Major Change by Luca on 31.03.2016.
 */
public enum StudentWorkMunich {
    MENSA_LEOPOLDSTRASSE,
    MENSA_MARTINSRIED,
    MENSA_GROSSHADERN,
    MENSA_ARCISSTRASSE,
    MENSA_GARCHING,
    MENSA_WEIHENSTEPHAN,
    MENSA_LOTHSTRASSE,
    MENSA_PASING,
    MENSA_ROSENHEIM,
    STUCAFE_ADALBERSTRASSE,
    STUCAFE_GARCHING,
    STUCAFE_AKADEMIE,
    STUCAFE_BOLTZMANNSTRASSE,
    STUCAFE_KARLSTRASSE
}
