language: java
jdk:
  - oraclejdk8

branches:
  only:
    - master

after_success:
  - mvn clean site cobertura:cobertura coveralls:report

notifications:
  email:
    recipients:
      - fhellmann@fs.cs.hm.edu
      - spataro@fs.cs.hm.edu
    on_success: change
    on_failure: always
