language: java
jdk:
  - oraclejdk7
  - oraclejdk8

after_success:
  - mvn clean cobertura:cobertura coveralls:report
  
notifications:
  email:
    recipients:
      - fhellmann@fs.cs.hm.edu
      - spataro@fs.cs.hm.edu
    on_success: change
    on_failure: always
